### ISSUE TITLE
MTMs book DTB17721 fails with an OutOfMemoryException during DTBook validation

### ISSUE THREAD

**Issue by josteinaj** [nlbdev/nordic-epub3-dtbook-migrator#309]
Probably due to the presence of 3649 headlines.

Detailed job log:
```
2015-03-19 14:16:40,591 [DEBUG] com.xmlcalabash.library.Sink - Running sink !1.21
2015-03-19 14:16:40,591 [INFO ] o.d.c.x.c.steps.Message$MessageStep - bundle://110.0:1/xml/xproc/message.xpl:116:29:DTBook Validator: Validating document: file:/home/jostein/Skrivebord/daisy-pipeline-1.9/data/jobs/95a32f5e-61f0-48e5-b62d-f43812f01d15/output/output-dir/DTB17721/DTB17721.xml
2015-03-19 14:16:40,592 [DEBUG] o.e.persistence.logging.default - Connection(508185471)--Thread(Thread[Thread-267,5,Configuration Admin Service])--INSERT INTO PERSISTENTMESSAGE (jobId, sequence, col, file, LEVEL, line, text, throwable, timestamp) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
	bind => [9 parameters bound]
2015-03-19 14:16:40,597 [DEBUG] com.xmlcalabash.library.DefaultStep - Running {http://www.daisy.org/ns/pipeline/xproc}log-message !1.23.2.1
2015-03-19 14:16:40,597 [DEBUG] com.xmlcalabash.library.Identity - Running identity result
2015-03-19 14:16:40,598 [DEBUG] c.x.library.ValidateWithSCH - Running validate-with-schematron validate-against-schematron
2015-03-19 14:23:37,863 [DEBUG] com.xmlcalabash.library.Identity - Running identity !1.25.2.2
2015-03-19 14:23:37,866 [DEBUG] com.xmlcalabash.library.Identity - Running identity !1.7.1.1
2015-03-19 14:23:37,866 [DEBUG] com.xmlcalabash.library.Sink - Running sink !1.24
2015-03-19 14:23:37,866 [DEBUG] com.xmlcalabash.library.Sink - Running sink !1.26
2015-03-19 14:23:37,866 [DEBUG] com.xmlcalabash.library.Sink - Running sink !1.21
2015-03-19 14:23:38,674 [DEBUG] com.xmlcalabash.library.ValidateJing - Running validate-with-relax-ng v-rng
2015-03-19 14:23:41,366 [DEBUG] o.a.h.i.c.PoolingClientConnectionManager - Connection manager is shutting down
2015-03-19 14:23:41,366 [DEBUG] o.a.h.i.c.PoolingClientConnectionManager - Connection manager shut down
```

Console output:
```
Exception in thread "Thread-267" java.lang.OutOfMemoryError: Java heap space
 at java.util.Arrays.copyOf(Arrays.java:2271)
 at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:113)
 at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
 at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:140)
 at net.sf.saxon.serialize.UTF8Writer.write(UTF8Writer.java:149)
 at net.sf.saxon.tree.tiny.CharSlice.write(CharSlice.java:224)
 at net.sf.saxon.serialize.XMLEmitter.writeCharSequence(XMLEmitter.java:652)
 at net.sf.saxon.serialize.XMLEmitter.writeEscape(XMLEmitter.java:743)
 at net.sf.saxon.serialize.XMLEmitter.characters(XMLEmitter.java:588)
 at net.sf.saxon.event.ProxyReceiver.characters(ProxyReceiver.java:193)
 at net.sf.saxon.event.ComplexContentOutputter.characters(ComplexContentOutputter.java:168)
 at net.sf.saxon.tree.tiny.TinyElementImpl.copy(TinyElementImpl.java:353)
 at net.sf.saxon.event.ComplexContentOutputter.append(ComplexContentOutputter.java:522)
 at net.sf.saxon.event.ComplexContentOutputter.append(ComplexContentOutputter.java:511)
 at net.sf.saxon.expr.Expression.process(Expression.java:581)
 at net.sf.saxon.query.XQueryExpression.run(XQueryExpression.java:425)
 at net.sf.saxon.s9api.XQueryEvaluator.run(XQueryEvaluator.java:326)
 at com.xmlcalabash.util.S9apiUtils.serialize(Unknown Source)
 at com.xmlcalabash.util.S9apiUtils.serialize(Unknown Source)
 at com.xmlcalabash.util.S9apiUtils.xdmToInputSource(Unknown Source)
 at com.xmlcalabash.library.ValidateJing.run(Unknown Source)
 at com.xmlcalabash.runtime.XAtomicStep.run(Unknown Source)
 at com.xmlcalabash.runtime.XCompoundStep.run(Unknown Source)
 at com.xmlcalabash.runtime.XTry.run(Unknown Source)
 at com.xmlcalabash.runtime.XPipeline.doRun(Unknown Source)
 at com.xmlcalabash.runtime.XPipeline.run(Unknown Source)
 at com.xmlcalabash.runtime.XPipelineCall.run(Unknown Source)
 at com.xmlcalabash.runtime.XCompoundStep.run(Unknown Source)
 at com.xmlcalabash.runtime.XPipeline.doRun(Unknown Source)
 at com.xmlcalabash.runtime.XPipeline.run(Unknown Source)
 at com.xmlcalabash.runtime.XPipelineCall.run(Unknown Source)
 at com.xmlcalabash.runtime.XCompoundStep.run(Unknown Source)
```

**Comment by josteinaj** [comment]
Replacing the XProc implementation that combines documents into the single-html document with a XSLT implementation seems to fix this.
